name: CD | Docker-Build-Release
on:
  push:
    branches:
      - "main"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: false
        default: "dev"
jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - run: depot build -t justinwlin/mistral7b:1.0 --build-arg MODEL_NAME="mistralai/Mistral-7B-v0.1" --build-arg BASE_PATH="/models" . --platform linux/amd64 --project 2x6lg48dzf --push
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
